<?php

return [
    'types'                       => [
        'image'    => [
            'allow_mimes'         => [
                'image/png'              => ['png'],
                'image/apng'             => ['png', 'apng'],
                'image/vnd.mozilla.apng' => ['png', 'apng'],
                'image/bmp'              => ['bmp'],
                'image/x-bmp'            => ['bmp', 'dib'],
                'image/gif'              => ['gif'],
                'image/jpeg'             => ['jpg', 'jpeg'],
                'image/pjpeg'            => ['jpg', 'jpeg'],
                'image/svg'              => ['svg'],
                'image/svg+xml'          => ['svg'],
                'image/webp'             => ['webp'],
            ],
            'max_file_size_mb'    => 10,
            'start_path'          => 'images',
            'disk'                => "public",
            'process_to_queue'    => false,
            'queue'               => 'file-process-images',
            'create_date_paths'   => true,
            'date_paths_with_day' => true,
        ],
        'video'    => [
            'allow_mimes'         => [
                'video/mp4'        => ['mp4'],
                'video/x-m4v'      => ['mp4'],
                'video/mp4v-es'    => ['mp4'],
                'video/x-matroska' => ['mkv'],
            ],
            'max_file_size_mb'    => 10,
            'start_path'          => 'videos',
            'disk'                => "public",
            'process_to_queue'    => false,
            'queue'               => 'file-process-videos',
            'create_date_paths'   => true,
            'date_paths_with_day' => true,
        ],
        'music'    => [
            'allow_mimes'         => [
                'audio/mp3'    => ['mp3'],
                'audio/x-mp3'  => ['mp3'],
                'audio/mpeg'   => ['mp3'],
                'audio/x-mpeg' => ['mp3'],
                'audio/x-mpg'  => ['mp3'],
            ],
            'max_file_size_mb'    => 10,
            'start_path'          => 'musics',
            'disk'                => "public",
            'process_to_queue'    => false,
            'queue'               => 'file-process-musics',
            'create_date_paths'   => true,
            'date_paths_with_day' => true,
        ],
        'document' => [
            'allow_mimes'         => [
                'application/pdf'                                                         => ['pdf'],
                'application/acrobat'                                                     => ['pdf'],
                'application/nappdf'                                                      => ['pdf'],
                'application/x-pdf'                                                       => ['pdf'],
                'image/pdf'                                                               => ['pdf'],
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document" => ['docx'],
            ],
            'max_file_size_mb'    => 10,
            'start_path'          => 'documents',
            'disk'                => "public",
            'process_to_queue'    => false,
            'queue'               => 'file-process-documents',
            'create_date_paths'   => true,
            'date_paths_with_day' => true,
        ],
        'program'  => [
            'allow_mimes'         => [
                'application/x-dosexec'                   => ['exe'],
                'application/vnd.android.package-archive' => ['apk'],
            ],
            'max_file_size_mb'    => 10,
            'start_path'          => 'programs',
            'disk'                => "public",
            'process_to_queue'    => false,
            'queue'               => 'file-process-programs',
            'create_date_paths'   => true,
            'date_paths_with_day' => true,
        ],
        'compress' => [
            'allow_mimes'         => [
                'application/zip'              => ['zip'],
                'application/x-zip'            => ['zip'],
                'application/x-zip-compressed' => ['zip'],
                'application/x-gzip'           => ['gz'],
                'application/gzip'             => ['gz'],
                'application/x-tar'            => ['tar'],
                'application/x-gtar'           => ['tar'],
                'application/x-rar-compressed' => ['rar'],
                'application/vnd.rar'          => ['rar'],
                'application/x-rar'            => ['rar'],
            ],
            'max_file_size_mb'    => 10,
            'start_path'          => 'compressed',
            'disk'                => "public",
            'process_to_queue'    => false,
            'queue'               => 'file-process-compress',
            'create_date_paths'   => true,
            'date_paths_with_day' => true,
        ],
        'other'    => [
            'allow_mimes'         => [
                'text/plain'               => ['txt', 'js', 'css', 'sql'],
                'text/html'                => ['html', 'js'],
                'text/x-php'               => ['php'],
                'application/octet-stream' => ['glb']
            ],
            'max_file_size_mb'    => 10,
            'start_path'          => 'others',
            'disk'                => "public",
            'process_to_queue'    => false,
            'queue'               => 'file-process-others',
            'create_date_paths'   => true,
            'date_paths_with_day' => true,
        ],
    ],
    'jobs'                        => [
        'upload' => \Sajadsdi\LaravelFileManagement\Jobs\Upload\UploadJob::class,
        'update' => '',
        'delete' => '',
        'trash'  => \Sajadsdi\LaravelFileManagement\Jobs\Trash\TrashJob::class,
        'restore_trash'  => \Sajadsdi\LaravelFileManagement\Jobs\Trash\RestoreTrashJob::class,
    ],
    'security'                    => [
        'secure_types' => ['program'],
        'secure_ext'   => 'secure',
    ],
    'trash'                       => [
        'start_path' => "trash",
        'disk' => "public",
        'process_to_queue' => false,
        'queue' => 'file-process-trash'
    ],
    'temp_path'                   => "temp",
    'require_check_ext_for_mimes' => ['application/octet-stream'],
];
